[tools]
go = "1.25.5"
opentofu = "1.11.4"
golangci-lint = "2.8.0"
"go:github.com/goph/licensei/cmd/licensei" = "v0.9.0"
"go:go.uber.org/mock/mockgen" = "v0.6.0"
"go:golang.org/x/tools/gopls" = "v0.20.0"
"go:golang.org/x/tools/cmd/goimports" = "0.38.0"
