[tools]
go-junit-report = "2.1.0"
pre-commit = "4.2.0"
gcloud = "535.0.0"
awscli = "2.28.15"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:golang.org/x/tools/gopls" = "v0.20.0"
tflint = "0.47.0"
terraform = "1.14.1"
pipx = { version = "1.8.0", os = ["macos", "linux"] }
"pipx:codespell" = { version = "2.4.1", os = ["macos", "linux"] }
