name: Announce Release
on:
  release:
    # This is intentionally not `published` to avoid announcing pre-releases
    types: [released]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag name of the release'
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Announce Release
        run: ./.github/scripts/announce-release.sh
        env:
          GH_TOKEN: ${{ github.token }}
          REPO: ${{ github.repository }}
          TAG_NAME: ${{ github.event.release.tag_name || inputs.tag_name }}
          URL: ${{ secrets.RELEASE_ANNOUNCEMENT_URL }}
          ROLE_ID: ${{ secrets.RELEASE_ANNOUNCEMENT_ROLE_ID }}
          USERNAME: ${{ secrets.RELEASE_ANNOUNCEMENT_USERNAME }}
          AVATAR_URL: ${{ secrets.RELEASE_ANNOUNCEMENT_AVATAR_URL }}
