name: Install Script Test

on:
  workflow_call:

jobs:
  install-script-test:
    name: Install Script Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run install script tests
        run: ./docs-starlight/tests/install_test.sh --quick
