name: Install Script Test

on:
  workflow_call:

jobs:
  install-script-test:
    name: Install Script Tests (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [blacksmith-4vcpu-ubuntu-2404, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install GPG (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y gnupg

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3

      - name: Run install script tests
        run: ./docs-starlight/tests/install_test.sh
